apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsidXNlcm5hbWUiOiJwYXJpdG9zaC1wcmFuamFsIiwicGFzc3dvcmQiOiJnaHBfMDB4dUcwbWdKRGtKaTdLdWlnUHZRSkRQb0h1cmI3NEdYUEV0IiwiZW1haWwiOiJwYXJpdG9zaC5wcmFuamFsQHplbW9zb2xhYnMuY29tIiwiYXV0aCI6ImNHRnlhWFJ2YzJndGNISmhibXBoYkRwbmFIQmZNREI0ZFVjd2JXZEtSR3RLYVRkTGRXbG5VSFpSU2tSUWIwaDFjbUkzTkVkWVVFVjAifX19
kind: Secret
metadata:
  creationTimestamp: "2024-04-18T13:21:32Z"
  name: ghcr-secret
  namespace: default
  resourceVersion: "536673"
  uid: ee1589e3-5cdf-4b16-929d-839a1b2ccfa2
type: kubernetes.io/dockerconfigjson
