apiVersion: apps/v1
kind: Deployment
metadata:
   name: backend-api-gateway-deployment
   labels:
      type: api-gateway-deployment
      app: backend-ag-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: api-gateway
  template:
    metadata:
      name: api-gateway-pod
      labels:
        type: api-gateway
    spec:
      containers:
      - name: pocketpay-backend-api-gateway
        image: ghcr.io/paritosh-pranjal/bc-pocketpay-backend-eks-api-gateway:4
        ports:
        - containerPort: 9191
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: http://service-registry-svc:8761/eureka/
          - name: EUREKA_INSTANCE_HOSTNAME
            value: api-gateway-svc

      imagePullSecrets: 
      - name: ghcr-secret
