apiVersion: v1
kind: Service
metadata:
  name: mysql-db-svc
  labels:
    app: mysql
spec:
  type: LoadBalancer
  ports:
  - targetPort: 3306
    port: 3306
  selector:
    type: mysql
    app: database-pod