name: Backend deployment
run-name: Backend deployment  triggered by ${{ github.actor }}

on:
  push:
    branches:
      - deployment
    paths:
      - .github/workflows/backendDeploy.yml
      - backend/**

env:
  GITHUB_USER: paritosh-pranjal

jobs:
  build:
    name: Backend Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/${{ matrix.services }}
    timeout-minutes: 10
    strategy:
      matrix:
        services:
          - api-gateway
          - business-service
          - service-registry
          - transaction-service
          - user-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.services }}-${{ hashFiles(join(matrix.services, '/**/pom.xml')) }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push the docker image to ghcr
        uses: docker/build-push-action@v4
        with:
          context: backend/${{ matrix.services }}
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/bc-pocketpay-backend-eks-${{ matrix.services }}:${{ github.run_number }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_EKS_REGION}}

      - name: Adding EKS cluster and Build and Deploy the service
        env:
          aws_region: ${{ secrets.AWS_EKS_REGION}}
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          SERVICE_NAME: ${{ matrix.services }}
        run: |
          aws eks --region $aws_region update-kubeconfig --name $cluster_name
          cd ${SERVICE_NAME}

          mvn clean package -Dmaven.test.skip=true
          SERVICE_NAME_LOWER=$(echo $SERVICE_NAME | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${{ env.GITHUB_USER }}/bc-128-backend-${SERVICE_NAME_LOWER}:${{ github.run_number }} .
          docker tag ghcr.io/${{ env.GITHUB_USER }}/bc-pocketpay-backend-eks-${SERVICE_NAME_LOWER}:${{ github.run_number }}
          docker push ghcr.io/${{ env.GITHUB_USER }}/bc-pocketpay-backend-eks-${SERVICE_NAME_LOWER}:${{ github.run_number }}
          kubectl set image deployment/${SERVICE_NAME_LOWER} ${SERVICE_NAME_LOWER}-container=ghcr.io/${{ env.GITHUB_USER }}/bc-pocketpay-backend-eks-${SERVICE_NAME_LOWER}:${{ github.run_number }}
    